
import { GoogleGenAI, GenerateContentResponse } from "@google/genai";

export class GeminiService {
  private ai: GoogleGenAI;

  constructor() {
    this.ai = new GoogleGenAI({ apiKey: process.env.API_KEY || '' });
  }

  /**
   * Generates a new image based on a reference image and a prompt.
   * @param base64Image The reference image in base64 format.
   * @param mimeType The MIME type of the reference image.
   * @param prompt The prompt describing the desired transformation or recreation.
   */
  async generateImageVariation(base64Image: string, mimeType: string, prompt: string): Promise<string | null> {
    try {
      // Remove the prefix (e.g., "data:image/png;base64,") if present
      const cleanBase64 = base64Image.replace(/^data:image\/\w+;base64,/, "");

      const response: GenerateContentResponse = await this.ai.models.generateContent({
        model: 'gemini-2.5-flash-image',
        contents: {
          parts: [
            {
              inlineData: {
                data: cleanBase64,
                mimeType: mimeType,
              },
            },
            {
              text: `Generate an image same like this one but following this specific instruction: ${prompt}. Maintain the core style, composition, and subject of the original image unless specified otherwise.`,
            },
          ],
        },
      });

      if (!response.candidates?.[0]?.content?.parts) {
        throw new Error("No image generated by the model.");
      }

      for (const part of response.candidates[0].content.parts) {
        if (part.inlineData) {
          return `data:image/png;base64,${part.inlineData.data}`;
        }
      }

      return null;
    } catch (error) {
      console.error("Error generating image variation:", error);
      throw error;
    }
  }
}

export const geminiService = new GeminiService();
